/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read the authenticated tenant's server-owned onboarding draft and completion state. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Persisted onboarding state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingState"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/steps/{step}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Save one validated onboarding step for the authenticated tenant. Owner-only. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    step: components["schemas"]["OnboardingStepNumber"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OnboardingStepRequest"];
                };
            };
            responses: {
                /** @description Onboarding step saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingState"];
                    };
                };
                /** @description Invalid step or step payload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Owner role required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Earlier steps are incomplete or onboarding is already complete */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Complete onboarding only after all eight persisted steps pass server validation. Owner-only. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CompleteOnboardingRequest"];
                };
            };
            responses: {
                /** @description Onboarding completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingCompletionResponse"];
                    };
                };
                /** @description Invalid completion request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Owner role required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description One or more required onboarding steps are incomplete */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Real self-serve signup — creates a Supabase Auth user, a tenants row with the full business/tax profile, and an owner staff_members row. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SignupRequest"];
                };
            };
            responses: {
                /** @description Signup successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description An account already exists with this email */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Email+password login via Supabase Auth. Derives role/tenantId from a server-side staff_members lookup. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Invalid email or password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List the caller's tenant's staff members. Requires manager or owner role. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of staff members */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Member"][];
                    };
                };
                /** @description Insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Invite a new staff member (manager or cashier) into the caller's tenant. Owner-only. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["InviteMemberRequest"];
                };
            };
            responses: {
                /** @description Invite sent and staff row created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Member"];
                    };
                };
                /** @description Insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{memberId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Change a staff member's role. Owner-only. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memberId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateMemberRoleRequest"];
                };
            };
            responses: {
                /** @description Role updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Member"];
                    };
                };
                /** @description Insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Member not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Soft-delete (deactivate) a staff member. Owner-only. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memberId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Member deactivated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Member"];
                    };
                };
                /** @description Insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Member not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List the caller's tenant's products with variants and current stock. Optional `search` filters to an exact-sku or partial-name match (CHECK-01/CHECK-02). */
        get: {
            parameters: {
                query?: {
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of products */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"][];
                    };
                };
            };
        };
        put?: never;
        /** @description Create a product with one or more variants (D-01/D-02). SKU auto-generated per variant unless supplied. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateProductRequest"];
                };
            };
            responses: {
                /** @description Product created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description SKU collision */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single product with its variants and current stock. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/variants/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Edit a variant. Price/reorderThreshold always editable; size/color/material blocked once stock has moved (D-04). */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: string;
                    variantId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateVariantRequest"];
                };
            };
            responses: {
                /** @description Variant updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Variant"];
                    };
                };
                /** @description Variant not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Variant identity is locked */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/stock-movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only movement history for a variant. */
        get: {
            parameters: {
                query: {
                    variantId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Movement history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StockMovement"][];
                    };
                };
                /** @description variantId is required */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** @description Record a stock movement (receive/adjustment/transfer). Adjustment requires manager or owner role (D-13). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateStockMovementRequest"];
                };
            };
            responses: {
                /** @description Movement recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StockMovement"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Insufficient permissions (adjustment requires manager+) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock-movements/low-stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Variants at or below their reorder threshold (INV-03). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Low-stock variants */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LowStockVariant"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/set-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description An authenticated staff member (owner, manager, or a newly-activated invited manager/cashier) provisions/changes their own PIN. Requires a real Supabase session (authMiddleware) — never the PIN-switch mechanism. Always targets the caller's own staff_members row. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SetPinRequest"];
                };
            };
            responses: {
                /** @description PIN set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                /** @description Invalid PIN */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No staff record found for this account */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/terminal/pin/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description PIN-switch the acting operator on a shared terminal. Requires an existing authenticated session (authMiddleware); does not create a new Supabase Auth session — issues a short-lived signed operator token instead (D-09/D-10). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PinSwitchRequest"];
                };
            };
            responses: {
                /** @description PIN-switch successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PinSwitchResponse"];
                    };
                };
                /** @description Incorrect PIN, locked out, or unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Look up prior sales by receipt number or customer search (D-09). Each returned sale includes its lines and payments. */
        get: {
            parameters: {
                query?: {
                    receiptNumber?: string;
                    customerSearch?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matching sales */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sale"][];
                    };
                };
            };
        };
        put?: never;
        /** @description Complete a checkout sale — server recomputes totals, enforces payment-sum, gates above-threshold discounts behind manager+ approval (D-05), writes sale+lines+payments+stock movements atomically. Response includes the sale's payments array. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateSaleRequest"];
                };
            };
            responses: {
                /** @description Sale completed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sale"];
                    };
                };
                /** @description Invalid request, variant not found, or payment sum mismatch */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Discount exceeds the tenant's manager-approval threshold and the acting role is not manager+ */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Target shift is already closed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/{saleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single sale with its line items and payments. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    saleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sale */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sale"];
                    };
                };
                /** @description Sale not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Process a partial or full return/refund against a prior sale (CHECK-07, D-09 through D-12). Writes a positive-delta return stock movement and refund payment row(s) against the original payment method — server-validated against the original sale's actual payment methods (D-10). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateReturnRequest"];
                };
            };
            responses: {
                /** @description Return processed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request, over-return, refund-sum mismatch, or refund method not used on the original sale */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Sale or line item not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Target shift is already closed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search customers by phone, email, or name (CUST-01, D-09). */
        get: {
            parameters: {
                query?: {
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matching customers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Customer"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/{saleId}/resend-receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Resend a receipt email for a completed sale (CHECK-06) — resolves a real target email and reports the actual send outcome. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    saleId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ResendReceiptRequest"];
                };
            };
            responses: {
                /** @description Receipt sent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResendReceiptResponse"];
                    };
                };
                /** @description No email address available */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Sale not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Email delivery failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Open a shift with a starting cash count (D-14). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OpenShiftRequest"];
                };
            };
            responses: {
                /** @description Shift opened */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Shift"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts/{shiftId}/x-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Live, non-resetting shift snapshot (D-15, CASH-02). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shiftId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description X report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["XReport"];
                    };
                };
                /** @description Shift not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts/{shiftId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Close a shift (Z report) — counted cash, variance, locks the shift (D-15/D-16). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shiftId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CloseShiftRequest"];
                };
            };
            responses: {
                /** @description Shift closed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZReport"];
                    };
                };
                /** @description Shift not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Shift already closed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OnboardingState: {
            data: components["schemas"]["OnboardingData"];
            currentStep: number;
            completed: boolean;
            /** Format: date-time */
            completedAt: string | null;
        };
        OnboardingData: {
            1?: components["schemas"]["OnboardingBusinessIdentityStep"];
            2?: components["schemas"]["OnboardingGstComplianceStep"];
            3?: components["schemas"]["OnboardingStoreSetupStep"];
            4?: components["schemas"]["OnboardingBillingInvoiceStep"];
            5?: components["schemas"]["OnboardingPaymentMethodsStep"];
            6?: components["schemas"]["OnboardingProductCatalogStep"];
            7?: components["schemas"]["OnboardingHardwareDevicesStep"];
            8?: components["schemas"]["OnboardingTeamAccessStep"];
        };
        OnboardingBusinessIdentityStep: {
            /** @enum {string} */
            storeCategory: "fashion" | "beauty" | "electronics" | "footwear" | "jewellery" | "books" | "pharmacy" | "grocery" | "multi";
            /** @enum {string} */
            trialPlan: "starter" | "growth" | "enterprise";
            /** @enum {string} */
            billingCycle: "monthly" | "annual";
            legalName: string;
            tradeName?: string;
            /** @enum {string} */
            businessStructure: "pvtltd" | "llp" | "partnership" | "proprietorship" | "public" | "huf" | "trust";
            yearEstablished: number;
            registrationNumber?: string;
            /** @enum {string} */
            natureOfBusiness: "retailer" | "wholesaler" | "both" | "mfr_retail" | "service";
            /** @enum {string} */
            storeCount: "1" | "2" | "3" | "4" | "5" | "6-10" | "11-20" | "20+";
        };
        OnboardingGstComplianceStep: {
            /** @enum {string} */
            gstStatus: "regular" | "composition" | "unregistered";
            gstin?: string;
            pan?: string;
            placeOfSupply: string;
            fssai?: string;
            drugLicense?: string;
            msmeRegistration?: string;
            shopEstablishmentLicense?: string;
            eInvoiceEnabled: boolean;
            eWayBillEnabled: boolean;
        };
        OnboardingStoreSetupStep: {
            storeName: string;
            addressLine1: string;
            addressLine2?: string;
            postalCode: string;
            city: string;
            state: string;
            /** @enum {string} */
            storeType: "mall_kiosk" | "mall_shop" | "high_street" | "standalone" | "airport" | "outlet";
            /** @enum {string} */
            storeClassification: "flagship" | "branch" | "franchise" | "popup";
            carpetAreaSqFt?: number;
            storeCode?: string;
            openingTime: string;
            managerName?: string;
            managerPhone?: string;
        };
        OnboardingBillingInvoiceStep: {
            invoicePrefix: string;
            invoiceStartNumber: number;
            /** @enum {string} */
            paymentTermsDays: "0" | "7" | "15" | "30" | "45" | "60";
            /** @enum {string} */
            gstPricingMode: "exclusive" | "inclusive";
            /** @enum {string} */
            defaultGstSlab: "0" | "5" | "12" | "18" | "28";
            /** @enum {string} */
            rounding: "nearest1" | "nearest50p" | "none";
            /** @enum {string} */
            financialYearStart: "april" | "jan";
            printHsn: boolean;
            printDuplicateCopy: boolean;
            invoiceQrEnabled: boolean;
            invoiceFooter?: string;
        };
        OnboardingPaymentMethodsStep: {
            cashEnabled: boolean;
            maxCashPerTransaction?: number;
            upiEnabled: boolean;
            /** @enum {string} */
            upiPartner?: "razorpay" | "phonepe" | "bharatpe" | "paytm" | "pinelabs_upi" | "googlepay";
            soundBoxEnabled: boolean;
            cardEnabled: boolean;
            /** @enum {string} */
            cardProvider?: "pinelabs" | "mosambee" | "mswipe" | "hdfc" | "payu" | "plural";
            contactlessEnabled: boolean;
            emiEnabled: boolean;
            giftCardEnabled: boolean;
            storeCreditEnabled: boolean;
            maxStoreCredit?: number;
            splitPaymentEnabled: boolean;
            advancePaymentEnabled: boolean;
        };
        OnboardingProductCatalogStep: {
            /** @enum {string} */
            skuCount: "under100" | "100-500" | "500-2000" | "2000-10000" | "10000plus";
            /** @enum {string} */
            importMethod: "csv" | "barcode" | "tally" | "manual";
            /** @enum {string} */
            unitOfMeasure: "piece" | "kg" | "gram" | "litre" | "ml" | "metre" | "box" | "pack" | "set" | "pair";
            /** @enum {string} */
            barcodeFormat: "ean13" | "code128" | "qr" | "upca" | "internal";
            hsnAutoLookup: boolean;
            mrpRequired: boolean;
            variantTracking: boolean;
            batchTracking: boolean;
            expiryTracking: boolean;
            serialTracking: boolean;
            serviceItemsEnabled: boolean;
            /** @enum {string} */
            negativeStockPolicy: "block" | "warn" | "allow";
        };
        OnboardingHardwareDevicesStep: {
            /** @enum {string} */
            billingCounters: "1" | "2" | "3" | "4" | "5" | "5plus";
            /** @enum {string} */
            printerConnection: "cloud" | "lan" | "bluetooth" | "none";
            /** @enum {string} */
            paperWidthMm?: "58" | "80";
            /** @enum {string} */
            scannerConnection: "usb" | "bluetooth" | "rf" | "none";
            /** @enum {string} */
            cashDrawerMode: "auto" | "manual" | "none";
            /** @enum {string} */
            cardTerminalType: "pinelabs" | "mosambee" | "order" | "none";
            customerDisplayEnabled: boolean;
            weighingScaleEnabled: boolean;
            labelPrinterEnabled: boolean;
            kitchenDisplayEnabled: boolean;
        };
        OnboardingTeamAccessStep: {
            approvalRules: {
                discountEnabled: boolean;
                discountThresholdPercent: number;
                refundEnabled: boolean;
                voidEnabled: boolean;
                settingsEnabled: boolean;
            };
            firstStaff?: {
                name: string;
                phone?: string;
                /** Format: email */
                email?: string;
                /** @enum {string} */
                accessLevel: "cashier" | "senior_cashier" | "floor_staff" | "manager";
                /** @enum {string} */
                defaultShift: "morning" | "mid" | "evening" | "full";
            };
            openingFloatPerCounter: number;
            endOfDayReminder: string;
            /** @enum {string} */
            autoClockOutHours: "8" | "10" | "12";
        };
        OnboardingStepNumber: number;
        OnboardingStepRequest: components["schemas"]["OnboardingBusinessIdentityStep"] | components["schemas"]["OnboardingGstComplianceStep"] | components["schemas"]["OnboardingStoreSetupStep"] | components["schemas"]["OnboardingBillingInvoiceStep"] | components["schemas"]["OnboardingPaymentMethodsStep"] | components["schemas"]["OnboardingProductCatalogStep"] | components["schemas"]["OnboardingHardwareDevicesStep"] | components["schemas"]["OnboardingTeamAccessStep"];
        OnboardingCompletionResponse: components["schemas"]["OnboardingState"] & {
            summary: {
                businessName: string;
                storeName: string;
                storeCategory: string;
                trialPlan: string;
                billingCounters: string;
                gstStatus: string;
            };
        };
        CompleteOnboardingRequest: Record<string, never>;
        AuthResponse: {
            user: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string;
                /** @enum {string} */
                role: "owner" | "manager" | "cashier";
                /** Format: uuid */
                tenantId: string;
            };
            session: {
                accessToken: string;
                refreshToken: string;
            };
        };
        SignupRequest: {
            /** Format: email */
            email: string;
            password: string;
            ownerName: string;
            businessName: string;
            addressLine1: string;
            addressLine2?: string;
            city: string;
            state: string;
            postalCode: string;
            /** @default US */
            country: string;
            taxId?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        Member: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            role: "owner" | "manager" | "cashier";
            isActive: boolean;
            createdAt: string;
        };
        InviteMemberRequest: {
            /** Format: email */
            email: string;
            name: string;
            /** @enum {string} */
            role: "manager" | "cashier";
        };
        UpdateMemberRoleRequest: {
            /** @enum {string} */
            role: "owner" | "manager" | "cashier";
        };
        Product: {
            /** Format: uuid */
            id: string;
            name: string;
            category: string | null;
            createdAt: string;
            variants: components["schemas"]["Variant"][];
        };
        Variant: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            productId: string;
            sku: string;
            size: string | null;
            color: string | null;
            material: string | null;
            price: string;
            reorderThreshold: number;
            identityLocked: boolean;
            currentStock: number;
            createdAt: string;
        };
        CreateProductRequest: {
            name: string;
            category?: string;
            variants: {
                sku?: string;
                size?: string;
                color?: string;
                material?: string;
                price: number;
                reorderThreshold?: number;
            }[];
        };
        UpdateVariantRequest: {
            size?: string;
            color?: string;
            material?: string;
            price?: number;
            reorderThreshold?: number;
        };
        StockMovement: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            variantId: string;
            /** @enum {string} */
            movementType: "sale" | "receive" | "adjustment" | "return" | "transfer";
            quantityDelta: number;
            /** @enum {string|null} */
            reasonCode: "damage" | "shrinkage_theft" | "count_correction" | "other" | null;
            reasonNote: string | null;
            /** Format: uuid */
            createdBy: string | null;
            createdAt: string;
        };
        CreateStockMovementRequest: {
            /** Format: uuid */
            variantId: string;
            /** @enum {string} */
            movementType: "receive" | "adjustment" | "transfer";
            quantityDelta: number;
            /** @enum {string} */
            reasonCode?: "damage" | "shrinkage_theft" | "count_correction" | "other";
            reasonNote?: string;
        };
        LowStockVariant: {
            /** Format: uuid */
            variantId: string;
            /** Format: uuid */
            productId: string;
            productName: string;
            sku: string;
            size: string | null;
            color: string | null;
            material: string | null;
            quantity: number;
            reorderThreshold: number;
        };
        SetPinRequest: {
            pin: string;
        };
        PinSwitchResponse: {
            operatorToken: string;
            staff: {
                id: string;
                /** @enum {string} */
                role: "owner" | "manager" | "cashier";
            };
        };
        PinSwitchRequest: {
            staffId: string;
            pin: string;
        };
        Sale: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            clientSaleId: string;
            /** Format: uuid */
            shiftId: string | null;
            /** Format: uuid */
            customerId: string | null;
            subtotal: string;
            discountAmount: string;
            taxAmount: string;
            totalAmount: string;
            status: string;
            /** Format: uuid */
            createdBy: string | null;
            createdAt: string;
            lines: components["schemas"]["SaleLineItem"][];
            payments: components["schemas"]["Payment"][];
            businessName?: string | null;
        };
        SaleLineItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            variantId: string;
            quantity: number;
            unitPrice: string;
            discountPercent: string | null;
            discountAmount: string;
            isTaxable: boolean;
            lineTotal: string;
        };
        Payment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            saleId: string;
            /** @enum {string} */
            method: "cash" | "card" | "check";
            /** @enum {string} */
            direction: "payment" | "refund";
            amount: string;
            referenceCode: string | null;
            /** Format: uuid */
            createdBy: string | null;
            createdAt: string;
        };
        CreateSaleRequest: {
            /** Format: uuid */
            clientSaleId: string;
            /** Format: uuid */
            shiftId: string;
            lines: {
                /** Format: uuid */
                variantId: string;
                quantity: number;
                discountPercent?: string;
                discountAmount?: string;
            }[];
            cartDiscountPercent?: string;
            cartDiscountAmount?: string;
            payments: components["schemas"]["PaymentInput"][];
            customer?: {
                /** Format: uuid */
                id?: string;
                name?: string;
                phone?: string;
                /** Format: email */
                email?: string;
            };
            /** Format: email */
            receiptEmail?: string;
        };
        PaymentInput: {
            /** @enum {string} */
            method: "cash" | "card" | "check";
            amount: string;
            referenceCode?: string;
        };
        CreateReturnRequest: {
            /** Format: uuid */
            saleId: string;
            /** Format: uuid */
            shiftId: string;
            lines: {
                /** Format: uuid */
                saleLineItemId: string;
                quantity: number;
            }[];
            refundPayments: {
                /** @enum {string} */
                method: "cash" | "card" | "check";
                amount: string;
                referenceCode?: string;
            }[];
        };
        Customer: {
            /** Format: uuid */
            id: string;
            name: string | null;
            phone: string | null;
            email: string | null;
            createdAt: string;
        };
        ResendReceiptResponse: {
            ok: boolean;
            /** Format: email */
            email: string;
        };
        ResendReceiptRequest: {
            /** Format: email */
            email?: string;
        };
        Shift: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            staffId: string;
            startingCash: string;
            openedAt: string;
            countedCash: string | null;
            variance: string | null;
            closedAt: string | null;
        };
        OpenShiftRequest: {
            startingCash: string;
        };
        XReport: {
            /** Format: uuid */
            shiftId: string;
            expectedCash: string;
            cashSalesTotal: string;
            cardSalesTotal: string;
            checkSalesTotal: string;
            refundsTotal: string;
            saleCount: number;
        };
        ZReport: components["schemas"]["XReport"] & {
            countedCash: string;
            variance: string;
            closedAt: string;
        };
        CloseShiftRequest: {
            countedCash: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
