'use client'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { apiClient } from '@/lib/api/client'
import { supabase } from '@/lib/supabase/client'
const DRAFT = 'couture.india.onboarding.unsent.selection'
const categories = [['👗','fashion','Fashion & Apparel','Clothing, ethnic wear, western'],['💄','beauty','Beauty & Wellness','Cosmetics, salon, spa'],['📱','electronics','Electronics & Gadgets','Phones, accessories, tech'],['👟','footwear','Footwear','Shoes, sandals, sports'],['💎','jewellery','Jewellery','Gold, diamond, fashion jewellery'],['📚','books','Books & Stationery','Books, gifts, office supplies'],['💊','pharmacy','Pharmacy & Healthcare','OTC medicine, wellness'],['🛒','grocery','Grocery & FMCG','Supermarket, convenience'],['🏪','multi','Multi-brand / Other','General retail, mixed categories']] as const
export default function StoreTypePage() { const router = useRouter(); const [selected, setSelected] = useState('fashion'); const [message, setMessage] = useState(''); useEffect(() => { const saved = JSON.parse(sessionStorage.getItem(DRAFT) ?? '{}'); setSelected(saved.storeCategory ?? 'fashion'); (async () => { const { data: { session } } = await supabase.auth.getSession(); if (!session?.access_token) return; const { data } = await apiClient.GET('/onboarding', { headers: { Authorization: `Bearer ${session.access_token}` } }); const persisted = data?.data[1]?.storeCategory; if (persisted) setSelected(persisted) })().catch(() => setMessage('Your saved category will be loaded when the connection is available.')) }, []); function continueSetup() { const saved = JSON.parse(sessionStorage.getItem(DRAFT) ?? '{}'); sessionStorage.setItem(DRAFT, JSON.stringify({ ...saved, storeCategory: selected })); router.push('/plans') } return <main className="min-h-screen bg-[#f5f6f7] px-5 py-10 text-[#0f1729] md:py-16"><div className="mx-auto max-w-5xl"><div className="mb-10 flex justify-center"><strong className="font-heading text-xl">Couture POS</strong></div><div className="text-center"><h1 className="font-heading text-4xl font-bold">What kind of store do you run?</h1><p className="mt-3 text-lg text-slate-500">We’ll configure GST slabs, HSN codes and catalog structure for your category.</p></div>{message && <p className="mt-4 text-center text-sm text-amber-700">{message}</p>}<div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map(([emoji,id,name,description]) => <button key={id} type="button" onClick={() => setSelected(id)} className={`min-h-40 rounded-2xl border-2 bg-white p-6 text-center shadow-sm ${selected === id ? 'border-[#0058BA] bg-[#eaf1fb]' : 'border-[#e6e8eb]'}`}><span className="text-3xl">{emoji}</span><strong className="mt-4 block">{name}</strong><span className="mt-1 block text-sm text-slate-500">{description}</span></button>)}</div><Button className="mx-auto mt-6 flex h-14 w-full max-w-sm text-base" onClick={continueSetup}>Continue →</Button></div></main> }
