'use client'
import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { createAdminBlogPost, listAdminBlogPosts, updateAdminBlogPost, type AdminBlogPost, type AdminBlogPostInput, type AdminContext } from '@/lib/admin-api'
import styles from './admin.module.css'

const blank: AdminBlogPostInput = { slug: '', title: '', excerpt: '', body: '', category: '', authorName: 'Ambel POS Editorial', coverImageUrl: '', seoTitle: '', seoDescription: '', status: 'draft' }
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 120)

export function AdminBlogView({ context, onError }: { context: AdminContext; onError: (message: string | null) => void }) {
  const [posts, setPosts] = useState<AdminBlogPost[]>([]), [editingId, setEditingId] = useState<string | null>(null)
  const [form, setForm] = useState(blank), [busy, setBusy] = useState(false), [success, setSuccess] = useState<string | null>(null)
  const canEdit = context.admin.role === 'platform_owner'
  async function load() { try { setPosts((await listAdminBlogPosts()).posts) } catch (e) { onError(e instanceof Error ? e.message : 'Blog posts could not be loaded.') } }
  useEffect(() => { void load() }, [])
  function edit(post: AdminBlogPost) { setEditingId(post.id); setForm({ slug: post.slug, title: post.title, excerpt: post.excerpt, body: post.body, category: post.category, authorName: post.author_name, coverImageUrl: post.cover_image_url ?? '', seoTitle: post.seo_title ?? '', seoDescription: post.seo_description ?? '', status: post.status }); setSuccess(null) }
  async function save(status: 'draft' | 'published') {
    if (!canEdit) return
    setBusy(true); setSuccess(null); onError(null)
    try { const payload = { ...form, status }; if (editingId) await updateAdminBlogPost(editingId, payload); else await createAdminBlogPost(payload); setSuccess(status === 'published' ? 'Published. The article is now available to the regional website and sitemap.' : 'Draft saved.'); setForm(blank); setEditingId(null); await load() }
    catch (e) { onError(e instanceof Error ? e.message : 'The blog post could not be saved.') } finally { setBusy(false) }
  }
  function submit(event: FormEvent, status: 'draft' | 'published') { event.preventDefault(); void save(status) }
  return <><h1 className={styles.heading}>Blog publishing</h1><p className={styles.subheading}>Write and publish for the {context.admin.region === 'IN' ? 'India' : 'International'} Ambel POS website. Posts never cross regional databases.</p>
    {success && <div className={styles.success} style={{ marginBottom: 16 }}>{success}</div>}
    {canEdit && <section className={styles.card}><div className={styles.cardHeader}><div><div className={styles.cardTitle}>{editingId ? 'Edit article' : 'New article'}</div><div className={styles.muted}>Use blank lines between paragraphs. Start subheadings with ##.</div></div>{editingId && <button className={styles.button} type="button" onClick={() => { setEditingId(null); setForm(blank) }}>Cancel edit</button>}</div><div className={styles.cardBody}><form onSubmit={(e) => submit(e, 'draft')}>
      <div className={styles.editorGrid}><Field label="Article title"><input className={styles.input} required maxLength={160} value={form.title} onChange={(e) => setForm(c => ({ ...c, title: e.target.value, slug: c.slug || slugify(e.target.value) }))} /></Field><Field label="URL slug"><input className={styles.input} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={120} value={form.slug} onChange={(e) => setForm(c => ({ ...c, slug: slugify(e.target.value) }))} /></Field><Field label="Category"><input className={styles.input} required maxLength={80} value={form.category} onChange={(e) => setForm(c => ({ ...c, category: e.target.value }))} /></Field><Field label="Author"><input className={styles.input} required maxLength={120} value={form.authorName} onChange={(e) => setForm(c => ({ ...c, authorName: e.target.value }))} /></Field></div>
      <Field label="Short summary"><textarea className={styles.textarea} required maxLength={320} value={form.excerpt} onChange={(e) => setForm(c => ({ ...c, excerpt: e.target.value }))} /></Field><Field label="Article"><textarea className={`${styles.textarea} ${styles.articleEditor}`} required maxLength={50000} value={form.body} onChange={(e) => setForm(c => ({ ...c, body: e.target.value }))} /></Field>
      <div className={styles.editorGrid}><Field label="Cover image URL (optional)"><input className={styles.input} type="url" value={form.coverImageUrl} onChange={(e) => setForm(c => ({ ...c, coverImageUrl: e.target.value }))} /></Field><Field label="Google title (optional, 70 max)"><input className={styles.input} maxLength={70} value={form.seoTitle} onChange={(e) => setForm(c => ({ ...c, seoTitle: e.target.value }))} /></Field></div><Field label="Google description (optional, 170 max)"><textarea className={styles.textarea} maxLength={170} value={form.seoDescription} onChange={(e) => setForm(c => ({ ...c, seoDescription: e.target.value }))} /></Field>
      <div className={styles.formRow}><button className={styles.button} disabled={busy} type="submit">Save draft</button><button className={`${styles.button} ${styles.primary}`} disabled={busy} type="button" onClick={() => void save('published')}>{busy ? 'Saving…' : 'Publish now'}</button></div>
    </form></div></section>}
    <section className={styles.card} style={{ marginTop: 16 }}><div className={styles.cardHeader}><div className={styles.cardTitle}>Regional articles</div><button className={styles.button} type="button" onClick={() => void load()}>Refresh</button></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Article</th><th>Status</th><th>Published</th><th>Updated</th></tr></thead><tbody>{posts.map(post => <tr key={post.id}><td>{canEdit ? <button className={styles.tableButton} type="button" onClick={() => edit(post)}>{post.title}</button> : <span className={styles.listMain}>{post.title}</span>}<div className={styles.listMeta}>/{context.admin.region === 'IN' ? 'blog' : 'us/blog'}/{post.slug} · {post.category}</div></td><td><span className={`${styles.badge} ${post.status === 'published' ? styles.badgeGreen : styles.badgeAmber}`}>{post.status}</span></td><td>{post.published_at ? new Date(post.published_at).toLocaleString() : '—'}</td><td>{new Date(post.updated_at).toLocaleString()}</td></tr>)}</tbody></table></div>{posts.length === 0 && <div className={styles.empty}>No articles yet. Create the first daily post above.</div>}</section></>
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className={styles.field}><span className={styles.label}>{label}</span>{children}</label> }
